### PR TITLE
feat: use ava instead of jest

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] use `npm` instead of [`yarn`](https://github.com/yarnpkg/yarn/issues/5521)
- [x]  use `ava` instead of `jest`
- [x] add nyc for tap reporting

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Hi @vinayakkulkarni 
I don't see advantages or why merge it

What do you think @pi0 ?

**Comment by vinayakkulkarni** [comment]
> Hi @vinayakkulkarni 
> I don't see advantages or why merge it
> 
> What do you think @pi0 ?

Hey Ricardo,

Maybe we can create two repositories for folks who want to make nuxt modules using Facebook's stack of jest, yarn and call it `nuxt-community/module-template-jest` and one with Facebook free template called `nuxt-community/module-template-ava`?

I had issues with Yarn not installing deps in production so I've switched to npm and there might be some folks who also prefer using npm but they may get stuck using yarn in the current scenario.

**Comment by ricardogobbosouza** [comment]
I thought of something like `create-nuxt-app` for modules
Where could you choose npm, yarn, jest, ava, babel, etc ...
Let's see what @pi0, @Atinux  think

**Comment by pi0** [comment]
Hi @vinayakkulkarni thanks for PR much appreciated. But this module template is based on Nuxt stack (which is mostly inspired by vue) and meant for consistent repos in `nuxt-community`. I would suggest keeping it as a fork.

@ricardogobbosouza For nuxt3 cli, we would unify to `npx nuxt module create` but it will use simple Github repo as template.

**Comment by vinayakkulkarni** [comment]
That's cool @pi0. I've added it to the [`awesome-nuxt`](https://github.com/nuxt-community/awesome-nuxt/pull/369) repo for folks to use.

Super excited about Nuxt 3, can't wait to contribute more in this awesome nuxt ecosystem!

**Pull request closed without merging**
