### PR TITLE
chore: remove babel

### LINKED ISSUE #43: Remove babel
No need babel configuration

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #43

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Ah yes, we would lose the `import` syntax in the tests

**Comment by ricardogobbosouza** [comment]
It's probably better to keep the babel
Initially the `module-template` does not use, but the user may want to use

**Comment by Atinux** [comment]
Then maybe adding just a mention in the documentation about the use of babel for tests?

**Comment by Atinux** [comment]
Also, I thought Jest was supporting `import` in the tests? 🤔

**Comment by pi0** [comment]
@Atinux Jest uses babel plugin for import support. I think for starter boilerplate would be better to keep it as default

**Comment by ricardogobbosouza** [comment]
Can closed?

**Pull request closed without merging**
